QUESTION 1

In [28]:
import numpy as np
import scipy as sc
from matplotlib import pyplot as plt

def dydt(y,t):
    return ((-2*y*t))

    dy/dt == (-2*y*t)


t = list(range(0,3))
y0 = 1

fig, (yt1,yt2) = plt.subplots(0,2)

plt.show()

ValueError: Number of rows must be a positive integer, not 0

<Figure size 640x480 with 0 Axes>

QUESTION 2

In [1]:
import numpy as np
import scipy as sc

A = np.array([[2,4,6], [5,3,2],[7,8,9]])

print(A)

[[2 4 6]
 [5 3 2]
 [7 8 9]]


In [18]:
B = np.array ([[18], [13], [30]])
              
print(B)

[[18]
 [13]
 [30]]


In [19]:
C = sc.linalg.solve(A, B)

print(C)

[[ 4.5]
 [-7.5]
 [ 6.5]]


QUESTION 3

In [22]:
import numpy as np
import matplotlib.pyplot as plt

import requests

def get_hourly_temperature(latitude, longitude, generationtime_ms, utc_offset_seconds, timezone_abbreviation, elevation, hourly_units):
    for temperature_info in data:
        if day_info["day"].lower() == day_name.lower():
            return temperature_info["hourly_temperature"]
        return None

def main():
    api_url = https://api.open-meteo.com/v1/forecast?latitude=2.5&longitude=112.5&hourly=temperature_2m&timezone=Asia%2FSingapore&forecast_days=1
        
    response = requests.get(api_url)
    
    if response.status.code == 200:
        data = response.json()
        
        while True:
            day = input("Enter the day (type 'exit' to end): ").
            
            if day.lower() == "exit":
                break
                
            hourly_temperature = get_hourly_temperature(day, data)
            
            if hourly_temperature is not None:
                print(f"Hourly temperature of {day}: {hourly_temperature}")
            else:
                print(f"{day} is not found in the data.")
        else:
            print(f"Failed to fetch data. Status code: {response.status_code}")
            
def plot_hourly_temperature(day, time):
    """
    Plot the temprature over day.
    
    Parameters: 
        latitude=2.375&longitude=112.5&timezone=Asia/Singapore()
        latitude (numpy.ndarray):
        longitude (numpu.ndarray):
     """
    plt.figure(figsize=(1, 17))
    plt.title("Hourly Temperature Over Days")
    plt.xlabel("Day")
    plt.ylabel("Temperature (C)")
    
    for i in range(1, len(time_values), len(time_values)//10):
        plt.plot(np.linspace(0, length, len(temperature[i, :])),
                temperature[i, :]: label=f'Time = {time_values[i]:.2f}s')
        
    plt.legend()
    plt.show()
    
    latitude = 2.375
    longitude = 112.5
    generationtime_ms = 0.032067298889160156
    utc_offset_seconds = 28800
    timezone = Asia/Singapore
    timezone_abbreviation = +08
    elevation = 272.0
    hourly_units = hour
    
    day_values,temperature_profile = hourly_temperature
    
    plot_hourly_temperature(day_values, temperature_profile)
    
    if__name__ == "__main__":
        main()

SyntaxError: invalid decimal literal (3418944368.py, line 13)